[build]
  publish = "."

# Redirects configuration
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[[redirects]]
  from = "/thank-you/"
  to = "/thank-you.html"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
